cc_binary(
  name = "analyzer_client",
  srcs = ["analyzer_client.cc"],
  deps = [
    "//protobuf:cc_proto",
    "//cpp/utils:protobuf_formatter",
    "//cpp/utils:protobuf_stream",
    "@grpc//:grpc++",
  ],
)