# package(default_visibility = ["//visibility:public"])

# load("@org_pubref_rules_protobuf//go:rules.bzl", "GRPC_COMPILE_DEPS")
# load("@io_bazel_rules_go//go:def.bzl", "go_binary", "go_library", "go_test")

# go_binary(
#     name = "frontend",
#     srcs = [
#         "main.go",
#         "utils.go",
#     ],
#     deps = [
#         "//protobuf:proto_go",
#     ] + GRPC_COMPILE_DEPS,
# )
