package(default_visibility = ["//cpp/analyzers:__subpackages__"])

cc_library(
  name = "analyzer_interface",
  hdrs = ["analyzer_interface.h"],
)

cc_library(
  name = "analyzer_service",
  hdrs = ["analyzer_service.h"],
  deps = ["@glog//:glog"]
)