cc_library(
    name = "word_count_analyzer",
    srcs = ["word_count_analyzer.cc"],
    hdrs = ["word_count_analyzer.h"],
    deps = ["//protobuf:proto_cc"],
    visibility = [
        "//cpp/analyzers/word_count/server:__pkg__",
        "//cpp/analyzers/word_count/test:__pkg__",
    ],
)
